version: "3.9"
services:
  datastudio:
    image: heartexlabs/label-studio:latest
    volumes:
      - "./data:/label-studio/data"
      - "./files:/label-studio/files"
    ports:
      - "50000:8080"
    environment:
      - LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED=true
      - LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT=/label-studio/files